name: deltasoft
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animations: ^2.0.1
  carousel_slider: ^4.0.0
  cart_stepper: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.3.8
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.5

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  hive_generator: ^1.1.1

flutter:
  uses-material-design: true
